<?php
session_start();
require_once __DIR__ . '/config.php';
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function base_data(){return ['settings'=>[],'services'=>[],'promotions'=>[],'products'=>[],'gallery'=>[],'bookings'=>[],'doctors'=>[],'reviews'=>[],'faqs'=>[]];}
function load_data(){if(!file_exists(MC_DATA_FILE))return base_data();$x=json_decode(file_get_contents(MC_DATA_FILE),true);return is_array($x)?array_merge(base_data(),$x):base_data();}
function save_data($x){if(!is_dir(dirname(MC_DATA_FILE)))mkdir(dirname(MC_DATA_FILE),0775,true);file_put_contents(MC_DATA_FILE,json_encode($x,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);} 
function make_id($p){return $p.time().rand(100,999);} 
function img_upload($field){if(empty($_FILES[$field])||($_FILES[$field]['error']??4)===4)return '';if($_FILES[$field]['error']!==0)return ''; $ok=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];$type=mime_content_type($_FILES[$field]['tmp_name']);if(!isset($ok[$type]))return '';if(!is_dir(MC_UPLOAD_DIR))mkdir(MC_UPLOAD_DIR,0775,true);$name=date('Ymd_His').'_'.bin2hex(random_bytes(3)).'.'.$ok[$type];$dest=MC_UPLOAD_DIR.'/'.$name;return move_uploaded_file($_FILES[$field]['tmp_name'],$dest)?MC_UPLOAD_URL.'/'.$name:'';}
function upload_list(){if(!is_dir(MC_UPLOAD_DIR))return []; $out=[]; foreach(scandir(MC_UPLOAD_DIR) as $f){if($f==='.'||$f==='..')continue; $p=MC_UPLOAD_DIR.'/'.$f; if(is_file($p))$out[]=['file'=>$f,'url'=>MC_UPLOAD_URL.'/'.$f,'size'=>filesize($p)];} return array_reverse($out);} 
$data=load_data();$msg='';
if(empty($_SESSION['mc_admin'])){header('Location: admin.php');exit;}
if(isset($_GET['backup'])){header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="site-backup.json"');echo json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(isset($_GET['csv'])){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="bookings.csv"');$fp=fopen('php://output','w');fputcsv($fp,['created','name','phone','gender','age','service','date','time','contact','message','status']);foreach($data['bookings']??[] as $b){fputcsv($fp,[$b['created_at']??'',$b['name']??'',$b['phone']??'',$b['gender']??'',$b['age']??'',$b['service']??'',$b['date']??'',$b['time']??'',$b['contact_method']??'',$b['message']??'',$b['status']??'']);}exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=$_POST['action']??'';
 if($a==='upload'){ $u=img_upload('image'); $msg=$u?'Uploaded: '.$u:'Upload failed'; }
 if(in_array($a,['doctors','reviews','faqs'],true)){ $id=make_id(substr($a,0,3)); if($a==='doctors'){$photo=img_upload('photo_file')?:trim($_POST['photo']??'');$item=['id'=>$id,'name'=>trim($_POST['name']??''),'name_kh'=>trim($_POST['name_kh']??''),'position'=>trim($_POST['position']??''),'position_kh'=>trim($_POST['position_kh']??''),'experience'=>trim($_POST['experience']??''),'experience_kh'=>trim($_POST['experience_kh']??''),'bio'=>trim($_POST['bio']??''),'bio_kh'=>trim($_POST['bio_kh']??''),'photo'=>$photo,'active'=>true];} elseif($a==='reviews'){$item=['id'=>$id,'name'=>trim($_POST['name']??''),'name_kh'=>trim($_POST['name_kh']??''),'service'=>trim($_POST['service']??''),'service_kh'=>trim($_POST['service_kh']??''),'rating'=>(int)($_POST['rating']??5),'review'=>trim($_POST['review']??''),'review_kh'=>trim($_POST['review_kh']??''),'active'=>true];} else {$item=['id'=>$id,'question'=>trim($_POST['question']??''),'question_kh'=>trim($_POST['question_kh']??''),'answer'=>trim($_POST['answer']??''),'answer_kh'=>trim($_POST['answer_kh']??''),'active'=>true];} $data[$a][]=$item;save_data($data);$msg='Saved'; }
}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin v3 tools</title><link rel="stylesheet" href="assets/style.css?v=3"><link rel="stylesheet" href="assets/v3.css?v=3"></head><body class="admin-body"><aside><div class="logo-mark">MC</div><h2>Admin v3</h2><a href="admin.php">Main Admin</a><a href="#images">Image Manager</a><a href="#bookings">Bookings</a><a href="#doctors">Specialists</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a><a href="#backup">Backup</a><a href="index.php" target="_blank">View Site</a></aside><main class="admin-main"><section class="admin-panel"><h1>Control Center</h1><?php if($msg):?><div class="notice"><?=e($msg)?></div><?php endif;?><div class="grid stats"><div><b><?=count(upload_list())?></b><span>Images</span></div><div><b><?=count($data['bookings']??[])?></b><span>Bookings</span></div><div><b><?=count($data['doctors']??[])?></b><span>Specialists</span></div><div><b><?=count($data['faqs']??[])?></b><span>FAQ</span></div></div></section>
<section id="images" class="admin-panel"><h2>Image Manager</h2><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="action" value="upload"><label>Upload image<input type="file" name="image" accept="image/*" required></label><button class="btn">Upload</button></form><div class="image-grid"><?php foreach(upload_list() as $img):?><div class="image-tile"><img src="<?=e($img['url'])?>"><code><?=e($img['url'])?></code><button class="small-btn" onclick="navigator.clipboard.writeText('<?=e($img['url'])?>')">Copy</button></div><?php endforeach;?></div></section>
<section id="bookings" class="admin-panel"><h2>Bookings</h2><p><a class="small-btn" href="?csv=1">Export CSV</a></p><div class="table-wrap"><table><tr><th>Date</th><th>Customer</th><th>Info</th></tr><?php foreach(array_reverse($data['bookings']??[]) as $b):?><tr><td><?=e($b['created_at']??'')?></td><td><b><?=e($b['name']??'')?></b><br><?=e($b['phone']??'')?></td><td><?=e($b['service']??'')?><br><?=e(($b['date']??'').' '.($b['time']??''))?><br><?=e(($b['gender']??'').' '.($b['age']??''))?><br><?=e($b['message']??'')?></td></tr><?php endforeach;?></table></div></section>
<section id="doctors" class="admin-panel"><h2>Doctor / Specialist</h2><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="action" value="doctors"><input name="name" placeholder="Name"><input name="name_kh" placeholder="Khmer name"><input name="position" placeholder="Position"><input name="position_kh" placeholder="Khmer position"><input name="experience" placeholder="Experience"><input name="experience_kh" placeholder="Khmer experience"><input name="photo" placeholder="Photo path"><input type="file" name="photo_file" accept="image/*"><textarea name="bio" placeholder="Bio"></textarea><textarea name="bio_kh" placeholder="Khmer bio"></textarea><button class="btn">Add Specialist</button></form></section>
<section id="reviews" class="admin-panel"><h2>Customer Reviews</h2><form method="post" class="admin-form"><input type="hidden" name="action" value="reviews"><input name="name" placeholder="Customer name"><input name="name_kh" placeholder="Khmer customer name"><input name="service" placeholder="Service"><input name="service_kh" placeholder="Khmer service"><input name="rating" type="number" min="1" max="5" value="5"><textarea name="review" placeholder="Review"></textarea><textarea name="review_kh" placeholder="Khmer review"></textarea><button class="btn">Add Review</button></form></section>
<section id="faq" class="admin-panel"><h2>FAQ</h2><form method="post" class="admin-form"><input type="hidden" name="action" value="faqs"><input name="question" placeholder="Question"><input name="question_kh" placeholder="Khmer question"><textarea name="answer" placeholder="Answer"></textarea><textarea name="answer_kh" placeholder="Khmer answer"></textarea><button class="btn">Add FAQ</button></form></section>
<section id="backup" class="admin-panel"><h2>Backup</h2><p><a class="btn" href="?backup=1">Download Backup</a></p></section></main></body></html>
