<?php
session_start();
require_once __DIR__ . '/config.php';
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function blank(){return ['settings'=>[],'services'=>[],'promotions'=>[],'products'=>[],'gallery'=>[],'bookings'=>[],'doctors'=>[],'reviews'=>[],'faqs'=>[]];}
function load_site(){if(!file_exists(MC_DATA_FILE))return blank();$x=json_decode(file_get_contents(MC_DATA_FILE),true);return is_array($x)?array_merge(blank(),$x):blank();}
function save_site($x){if(!is_dir(dirname(MC_DATA_FILE)))mkdir(dirname(MC_DATA_FILE),0775,true);file_put_contents(MC_DATA_FILE,json_encode($x,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);} 
function nid($p){return $p.time().rand(100,999);} 
function idx($items,$id){foreach($items as $i=>$x){if(($x['id']??'')===$id)return $i;}return -1;}
function upload_img($field){if(empty($_FILES[$field])||($_FILES[$field]['error']??4)===4)return '';if($_FILES[$field]['error']!==0)return ''; $ok=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];$type=mime_content_type($_FILES[$field]['tmp_name']);if(!isset($ok[$type]))return '';if(!is_dir(MC_UPLOAD_DIR))mkdir(MC_UPLOAD_DIR,0775,true);$name=date('Ymd_His').'_'.bin2hex(random_bytes(3)).'.'.$ok[$type];$dest=MC_UPLOAD_DIR.'/'.$name;return move_uploaded_file($_FILES[$field]['tmp_name'],$dest)?MC_UPLOAD_URL.'/'.$name:'';}
function files_list(){if(!is_dir(MC_UPLOAD_DIR))return []; $out=[]; foreach(scandir(MC_UPLOAD_DIR) as $f){if($f==='.'||$f==='..')continue; $p=MC_UPLOAD_DIR.'/'.$f; if(is_file($p))$out[]=['file'=>$f,'url'=>MC_UPLOAD_URL.'/'.$f,'size'=>filesize($p)];} return array_reverse($out);} 
$data=load_site();$flash='';
if(empty($_SESSION['mc_admin'])){header('Location: admin.php');exit;}
if(isset($_GET['backup'])){header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="site-backup-'.date('Ymd-His').'.json"');echo json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(isset($_GET['csv'])){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="bookings-'.date('Ymd-His').'.csv"');$fp=fopen('php://output','w');fputcsv($fp,['created_at','name','phone','gender','age','service','date','time','contact_method','message','status','admin_note']);foreach($data['bookings']??[] as $b){fputcsv($fp,[$b['created_at']??'',$b['name']??'',$b['phone']??'',$b['gender']??'',$b['age']??'',$b['service']??'',$b['date']??'',$b['time']??'',$b['contact_method']??'',$b['message']??'',$b['status']??'',$b['admin_note']??'']);}exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=$_POST['action']??'';
 if($a==='upload_image'){ $u=upload_img('image_file'); $flash=$u?'Uploaded: '.$u:'Upload failed. Use JPG, PNG, WEBP, or GIF.'; }
 if($a==='delete_image'){ $f=basename($_POST['file']??''); $p=MC_UPLOAD_DIR.'/'.$f; if(is_file($p)){unlink($p);$flash='Image deleted.';} }
 if($a==='restore_backup' && !empty($_FILES['backup_file']['tmp_name'])){ $raw=file_get_contents($_FILES['backup_file']['tmp_name']); $json=json_decode($raw,true); if(is_array($json)){save_site(array_merge(blank(),$json));$data=load_site();$flash='Backup restored.';} else $flash='Invalid JSON backup.'; }
 if($a==='save_booking_note'){ $id=$_POST['id']??''; $i=idx($data['bookings']??[],$id); if($i>=0){$data['bookings'][$i]['status']=trim($_POST['status']??'New');$data['bookings'][$i]['admin_note']=trim($_POST['admin_note']??'');save_site($data);$flash='Booking updated.';} }
 if(in_array($a,['doctor','review','faq'],true)){
   $sec=$a==='doctor'?'doctors':($a==='review'?'reviews':'faqs'); $id=trim($_POST['id']??'')?:nid(substr($a,0,3)); $i=idx($data[$sec]??[],$id);
   if($a==='doctor'){$photo=upload_img('photo_file')?:trim($_POST['photo']??'');$item=['id'=>$id,'name'=>trim($_POST['name']??''),'name_kh'=>trim($_POST['name_kh']??''),'position'=>trim($_POST['position']??''),'position_kh'=>trim($_POST['position_kh']??''),'experience'=>trim($_POST['experience']??''),'experience_kh'=>trim($_POST['experience_kh']??''),'bio'=>trim($_POST['bio']??''),'bio_kh'=>trim($_POST['bio_kh']??''),'photo'=>$photo,'active'=>!empty($_POST['active'])];}
   elseif($a==='review'){$item=['id'=>$id,'name'=>trim($_POST['name']??''),'name_kh'=>trim($_POST['name_kh']??''),'service'=>trim($_POST['service']??''),'service_kh'=>trim($_POST['service_kh']??''),'rating'=>(int)($_POST['rating']??5),'review'=>trim($_POST['review']??''),'review_kh'=>trim($_POST['review_kh']??''),'active'=>!empty($_POST['active'])];}
   else{$item=['id'=>$id,'question'=>trim($_POST['question']??''),'question_kh'=>trim($_POST['question_kh']??''),'answer'=>trim($_POST['answer']??''),'answer_kh'=>trim($_POST['answer_kh']??''),'active'=>!empty($_POST['active'])];}
   if($i>=0)$data[$sec][$i]=$item;else $data[$sec][]=$item;save_site($data);$flash='Saved.';
 }
 if($a==='delete_item'){ $sec=$_POST['section']??''; $id=$_POST['id']??''; if(isset($data[$sec])){$data[$sec]=array_values(array_filter($data[$sec],fn($x)=>($x['id']??'')!==$id));save_site($data);$flash='Deleted.';} }
}
$status=$_GET['status']??'all';$bookings=array_reverse($data['bookings']??[]);if($status!=='all')$bookings=array_values(array_filter($bookings,fn($b)=>($b['status']??'New')===$status));
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin v3</title><link rel="stylesheet" href="assets/style.css?v=3"></head><body class="admin-body"><aside><div class="logo-mark">MC</div><h2>Admin v3</h2><a href="admin.php">Main Admin</a><a href="#images">Image Manager</a><a href="#booking">Bookings</a><a href="#doctors">Specialists</a><a href="#reviews">Reviews</a><a href="#faq">FAQ</a><a href="#backup">Backup</a><a href="index.php" target="_blank">View Site</a></aside><main class="admin-main"><section class="admin-panel"><h1>v3 Control Center</h1><?php if($flash):?><div class="notice"><?=e($flash)?></div><?php endif;?><div class="grid stats"><div><b><?=count(files_list())?></b><span>Images</span></div><div><b><?=count($data['bookings']??[])?></b><span>Bookings</span></div><div><b><?=count($data['doctors']??[])?></b><span>Specialists</span></div><div><b><?=count($data['faqs']??[])?></b><span>FAQ</span></div></div></section>
<section id="images" class="admin-panel"><h2>Image Manager</h2><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="action" value="upload_image"><label>Upload image<input type="file" name="image_file" accept="image/*" required></label><button class="btn">Upload</button></form><div class="image-grid"><?php foreach(files_list() as $img):?><div class="image-tile"><img src="<?=e($img['url'])?>"><code><?=e($img['url'])?></code><button class="small-btn" onclick="navigator.clipboard.writeText('<?=e($img['url'])?>')">Copy</button><form method="post" onsubmit="return confirm('Delete image?')"><input type="hidden" name="action" value="delete_image"><input type="hidden" name="file" value="<?=e($img['file'])?>"><button class="small-btn danger">Delete</button></form></div><?php endforeach;?></div></section>
<section id="booking" class="admin-panel"><h2>Booking Manager</h2><p><a class="small-btn" href="admin_v3.php?csv=1">Export CSV</a> <a class="small-btn" href="?status=all#booking">All</a> <a class="small-btn" href="?status=New#booking">New</a> <a class="small-btn" href="?status=Contacted#booking">Contacted</a> <a class="small-btn" href="?status=Completed#booking">Completed</a></p><div class="table-wrap"><table><tr><th>Date</th><th>Customer</th><th>Info</th><th>Status</th><th>Admin Note</th><th>Save</th></tr><?php foreach($bookings as $b):?><tr><td><?=e($b['created_at']??'')?></td><td><b><?=e($b['name']??'')?></b><br><?=e($b['phone']??'')?></td><td><?=e($b['service']??'')?><br><?=e(($b['date']??'').' '.($b['time']??''))?><br><?=e(($b['gender']??'').' '.($b['age']??''))?><br><?=e($b['contact_method']??'')?><br><?=e($b['message']??'')?></td><td><?=e($b['status']??'New')?></td><td colspan="2"><form method="post" class="inline-edit"><input type="hidden" name="action" value="save_booking_note"><input type="hidden" name="id" value="<?=e($b['id']??'')"><select name="status"><option>New</option><option>Contacted</option><option>Completed</option><option>Cancelled</option></select><textarea name="admin_note"><?=e($b['admin_note']??'')?></textarea><button class="small-btn">Save</button></form></td></tr><?php endforeach;?></table></div></section>
<section id="doctors" class="admin-panel"><h2>Doctor / Specialist</h2><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="action" value="doctor"><input name="name" placeholder="Name"><input name="name_kh" placeholder="Khmer name"><input name="position" placeholder="Position"><input name="position_kh" placeholder="Khmer position"><input name="experience" placeholder="Experience"><input name="experience_kh" placeholder="Khmer experience"><input name="photo" placeholder="Photo path"><input type="file" name="photo_file" accept="image/*"><textarea name="bio" placeholder="Bio"></textarea><textarea name="bio_kh" placeholder="Khmer bio"></textarea><label class="check"><input type="checkbox" name="active" checked> Active</label><button class="btn">Add Specialist</button></form><?php tbl('doctors',$data,['name','position','experience']);?></section>
<section id="reviews" class="admin-panel"><h2>Customer Reviews</h2><form method="post" class="admin-form"><input type="hidden" name="action" value="review"><input name="name" placeholder="Customer name"><input name="name_kh" placeholder="Khmer customer name"><input name="service" placeholder="Service"><input name="service_kh" placeholder="Khmer service"><input name="rating" type="number" min="1" max="5" value="5"><textarea name="review" placeholder="Review"></textarea><textarea name="review_kh" placeholder="Khmer review"></textarea><label class="check"><input type="checkbox" name="active" checked> Active</label><button class="btn">Add Review</button></form><?php tbl('reviews',$data,['name','service','rating']);?></section>
<section id="faq" class="admin-panel"><h2>FAQ</h2><form method="post" class="admin-form"><input type="hidden" name="action" value="faq"><input name="question" placeholder="Question"><input name="question_kh" placeholder="Khmer question"><textarea name="answer" placeholder="Answer"></textarea><textarea name="answer_kh" placeholder="Khmer answer"></textarea><label class="check"><input type="checkbox" name="active" checked> Active</label><button class="btn">Add FAQ</button></form><?php tbl('faqs',$data,['question','answer']);?></section>
<section id="backup" class="admin-panel"><h2>Backup / Restore</h2><p><a class="btn" href="admin_v3.php?backup=1">Download Backup</a></p><form method="post" enctype="multipart/form-data" class="admin-form"><input type="hidden" name="action" value="restore_backup"><label>Restore JSON backup<input type="file" name="backup_file" accept="application/json" required></label><button class="btn danger">Restore</button></form></section></main></body></html>
<?php function tbl($sec,$data,$cols){echo '<div class="table-wrap"><table><tr>';foreach($cols as $c)echo '<th>'.e($c).'</th>';echo '<th>Action</th></tr>';foreach(($data[$sec]??[]) as $r){echo '<tr>';foreach($cols as $c)echo '<td>'.e($r[$c]??'').'</td>';echo '<td><form method="post" onsubmit="return confirm(\'Delete?\')"><input type="hidden" name="action" value="delete_item"><input type="hidden" name="section" value="'.e($sec).'"><input type="hidden" name="id" value="'.e($r['id']??'').'"><button class="small-btn danger">Delete</button></form></td></tr>';}echo '</table></div>';}
?>
