<?php
session_start();
require_once __DIR__ . '/config.php';
function d(){return ['settings'=>[],'services'=>[],'gallery'=>[],'faqs'=>[]];}
function load_site(){if(!file_exists(MC_DATA_FILE))return d();$x=json_decode(file_get_contents(MC_DATA_FILE),true);return is_array($x)?array_merge(d(),$x):d();}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function a($items){return array_values(array_filter($items??[],fn($x)=>!isset($x['active'])||$x['active']));}
function lv($x,$k,$l,$f=''){return $l==='kh'&&!empty($x[$k.'_kh'])?$x[$k.'_kh']:($x[$k]??$f);} 
$data=load_site();$lang=($_GET['lang']??$_SESSION['mc_lang']??'en')==='kh'?'kh':'en';$_SESSION['mc_lang']=$lang;$id=$_GET['id']??'';$item=null;foreach(($data['services']??[]) as $s){if(($s['id']??'')===$id){$item=$s;break;}}if(!$item){http_response_code(404);echo 'Service not found';exit;}$settings=$data['settings']??[];$title=lv($item,'name',$lang,'Service');$related=array_filter(a($data['gallery']??[]),fn($g)=>empty($g['service'])||stripos($g['service'],$item['name']??'')!==false);$faqs=a($data['faqs']??[]);
?>
<!doctype html><html lang="<?=e($lang)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> - <?=e(lv($settings,'clinic_name',$lang,'Clinic'))?></title><meta name="description" content="<?=e(lv($item,'description',$lang,''))?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Kantumruy+Pro:wght@300;400;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css?v=3"></head><body><header class="nav"><a class="brand" href="index.php"><span>MC</span><b><?=e(lv($settings,'clinic_name',$lang,'Clinic'))?></b></a><nav><a href="index.php#services">Services</a><a href="index.php#booking">Booking</a><a class="lang" href="?id=<?=e($id)?>&lang=<?=$lang==='kh'?'en':'kh'?>"><?=$lang==='kh'?'EN':'ខ្មែរ'?></a></nav></header><section class="service-hero"><div><p class="eyebrow"><?=e(lv($item,'category',$lang,''))?></p><h1><?=e($title)?></h1><p><?=e(lv($item,'description',$lang,''))?></p><b class="price-tag"><?=e($item['price']??'Contact')?></b><div class="hero-actions"><a class="btn" href="index.php#booking">Book this service</a><a class="btn ghost" href="index.php">Back home</a></div></div><?php if(!empty($item['image'])):?><img src="<?=e($item['image'])?>" alt="<?=e($title)?>"><?php endif;?></section><section class="section soft"><h2 class="center">Benefits</h2><div class="grid cards"><article class="card"><h3>Natural Result</h3><p>Designed for a balanced and fresh appearance.</p></article><article class="card"><h3>Consultation First</h3><p>Client condition is checked before treatment.</p></article><article class="card"><h3>Premium Care</h3><p>Clean clinic process and after-care guidance.</p></article></div></section><?php if($related):?><section class="section"><h2 class="center">Related Results</h2><div class="grid results"><?php foreach($related as $g):?><article class="result"><div class="ba"><div><?php if(!empty($g['before'])):?><img src="<?=e($g['before'])?>"><?php else:?><span>Before</span><?php endif;?></div><div><?php if(!empty($g['after'])):?><img src="<?=e($g['after'])?>"><?php else:?><span>After</span><?php endif;?></div></div><h3><?=e(lv($g,'title',$lang,''))?></h3><p><?=e(lv($g,'note',$lang,'Results may vary.'))?></p></article><?php endforeach;?></div></section><?php endif;?><?php if($faqs):?><section class="section soft"><h2 class="center">FAQ</h2><div class="faq-list"><?php foreach($faqs as $f):?><details><summary><?=e(lv($f,'question',$lang,''))?></summary><p><?=e(lv($f,'answer',$lang,''))?></p></details><?php endforeach;?></div></section><?php endif;?><footer><b><?=e(lv($settings,'clinic_name',$lang,'Clinic'))?></b></footer></body></html>
